import React from "react";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "../globals.css"
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={cn(inter.className, "flex items-center justify-center h-screen text-white")} >{children}</body>
      </html>
    </ClerkProvider>
  );
}
